CREATE OR REPLACE PACKAGE BCM_ORDER_MGMT_PKG_TEST AS
    PROCEDURE TEST_FORMAT_ORDER_REFERENCE;
    PROCEDURE TEST_FORMAT_TOTAL_AMOUNT;
    PROCEDURE TEST_CONVERT_ANY_DATE;
    PROCEDURE TEST_GET_SUPPLIER_ORDER_SUMMARY;
    PROCEDURE TEST_GET_MEDIAN_ORDER_DETAILS;
    PROCEDURE TEST_MIGRATE_BCM_ORDER_MGT;
END BCM_ORDER_MGMT_PKG_TEST;
/

CREATE OR REPLACE PACKAGE BODY BCM_ORDER_MGMT_PKG_TEST AS

    PROCEDURE TEST_FORMAT_ORDER_REFERENCE IS
        v_result NUMBER;
    BEGIN
        v_result := BCM_ORDER_MGMT_PKG.FORMAT_ORDER_REFERENCE('PO123');
        DBMS_OUTPUT.PUT_LINE('Test FORMAT_ORDER_REFERENCE: Expected 123, Got: ' || v_result);
    END TEST_FORMAT_ORDER_REFERENCE;

    PROCEDURE TEST_FORMAT_TOTAL_AMOUNT IS
        v_result VARCHAR2(20);
    BEGIN
        v_result := BCM_ORDER_MGMT_PKG.FORMAT_TOTAL_AMOUNT('10000');
        DBMS_OUTPUT.PUT_LINE('Test FORMAT_TOTAL_AMOUNT: Expected 10,000.00, Got: ' || v_result);
    END TEST_FORMAT_TOTAL_AMOUNT;

    PROCEDURE TEST_CONVERT_ANY_DATE IS
        v_result VARCHAR2(20);
    BEGIN
        v_result := BCM_ORDER_MGMT_PKG.CONVERT_ANY_DATE('06-07-2024', 'DD-MON-YYYY');
        DBMS_OUTPUT.PUT_LINE('Test CONVERT_ANY_DATE: Expected 06-JUL-2024, Got: ' || v_result);
    END TEST_CONVERT_ANY_DATE;

    PROCEDURE TEST_GET_SUPPLIER_ORDER_SUMMARY IS
    BEGIN
        BCM_ORDER_MGMT_PKG.GET_SUPPLIER_ORDER_SUMMARY;
        DBMS_OUTPUT.PUT_LINE('Test GET_SUPPLIER_ORDER_SUMMARY executed.');
    END TEST_GET_SUPPLIER_ORDER_SUMMARY;

    PROCEDURE TEST_GET_MEDIAN_ORDER_DETAILS IS
    BEGIN
        BCM_ORDER_MGMT_PKG.GET_MEDIAN_ORDER_DETAILS;
        DBMS_OUTPUT.PUT_LINE('Test GET_MEDIAN_ORDER_DETAILS executed.');
    END TEST_GET_MEDIAN_ORDER_DETAILS;

    PROCEDURE TEST_MIGRATE_BCM_ORDER_MGT IS
    BEGIN
        BCM_ORDER_MGMT_PKG.MIGRATE_BCM_ORDER_MGT;
        DBMS_OUTPUT.PUT_LINE('Test MIGRATE_BCM_ORDER_MGT executed.');
    END TEST_MIGRATE_BCM_ORDER_MGT;

END BCM_ORDER_MGMT_PKG_TEST;
/

BEGIN
    BCM_ORDER_MGMT_PKG_TEST.TEST_FORMAT_ORDER_REFERENCE;
    BCM_ORDER_MGMT_PKG_TEST.TEST_FORMAT_TOTAL_AMOUNT;
    BCM_ORDER_MGMT_PKG_TEST.TEST_CONVERT_ANY_DATE;
    BCM_ORDER_MGMT_PKG_TEST.TEST_GET_SUPPLIER_ORDER_SUMMARY;
    BCM_ORDER_MGMT_PKG_TEST.TEST_GET_MEDIAN_ORDER_DETAILS;
    BCM_ORDER_MGMT_PKG_TEST.TEST_MIGRATE_BCM_ORDER_MGT;
END;
/